# Generated by Django 3.0.2 on 2020-01-13 15:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Bounding box')),
                ('overlays_count', models.IntegerField(default=0, verbose_name='Overlays counter')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Layer',
                'verbose_name_plural': 'Layers',
            },
        ),
        migrations.CreateModel(
            name='Rhodonea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=1000, verbose_name='Name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Point')),
                ('r', models.FloatField(verbose_name='R')),
                ('n', models.FloatField(verbose_name='n')),
                ('d', models.FloatField(verbose_name='d')),
                ('rotation', models.FloatField(verbose_name='Rotation')),
                ('nodes_count', models.IntegerField(verbose_name='Nodes Count')),
                ('stroke_color', models.CharField(default='#000000', max_length=10, verbose_name='Stroke color')),
                ('stroke_weight', models.FloatField(default=1.0, verbose_name='Stroke weight')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rhodoneas', to='rhodonea_mapper.Layer')),
            ],
            options={
                'verbose_name': 'Rhodonea',
                'verbose_name_plural': 'Rhodoneas',
            },
        ),
    ]
